input {
  tcp {
    port => 5000
    codec => json_lines
  }
  beats {
    port => 5044
  }
}

filter {
  if [application] == "momentum" {
    mutate {
      add_field => { "[@metadata][index]" => "momentum-%{+YYYY.MM.dd}" }
    }
  }
  date {
    match => ["@timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index]}"
    manage_template => false
  }
  stdout {
    codec => rubydebug
  }
}
